name = "CausalGraphs"
uuid = "5b34ff98-3cd7-4491-9f4d-e18b2747e292"
version = "0.1.0"
authors = ["S. Celles"]

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
MakieCore = "20f20a25-4f0e-4fdf-b5d1-57303727442b"

[extensions]
CausalGraphsMakieExt = "MakieCore"

[compat]
JSON = "1.7.1"
MakieCore = "0.10.0"
UUIDs = "1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
